import numpy as np
import pandas as pd

ally_reflections = [
    "The forest feels like a second home.",
    "Hiking clears my head more than anything else.",
    "The color green is always calming.",
    "I wish I could live in a little cabin surrounded by trees.",
    "That feeling when you reach the summit is unbeatable.",
    "I love how moss makes everything look ancient and wise.",
    "Green tea and green forests just match.",
    "Sometimes I think trees are better company than people.",
    "I want to hike every national park one day.",
    "My backpack always feels heavier at the start than the end.",
    "Why do socks always get wet when you hike near rivers?",
    "Sunlight through the leaves looks like stained glass.",
    "I always spot heart-shaped leaves when I need them most.",
    "Trail mix never tastes as good as when you’re on the trail.",
    "I’d rather walk uphill forever than deal with downhill knee pain.",
    "Wildflowers feel like tiny celebrations along the path.",
    "I think I collect too many rocks… but they’re all different!",
    "I always feel small but strong in the mountains.",
    "The sound of wind through trees beats city noise every time.",
    "Hiking boots are the best investment I’ve ever made.",
    "Why do bugs love me so much?",
    "Ferns look like little green feathers.",
    "A hike with friends always feels shorter.",
    "I secretly love the smell of damp soil.",
    "Green is not just a color; it’s a feeling.",
    "My water bottle is my most loyal companion.",
    "I think I might have more pictures of trees than people.",
    "Hiking makes me notice details I’d otherwise miss.",
    "I love how fog makes forests feel like a fairy tale.",
    "Why do I always underestimate how steep a 'moderate' trail is?",
    "The best naps are after long hikes.",
    "I want to try thru-hiking one day.",
    "The first sip of water after a climb feels sacred.",
    "Mushrooms look like little umbrellas for fairies.",
    "My favorite shade of green is pine.",
    "I could spend hours just listening to a river.",
    "Why do gnats swarm my face and not anyone else’s?",
    "The forest smells different after rain.",
    "A green canopy feels like nature’s cathedral.",
    "I like how hiking makes me forget my phone exists.",
    "Sometimes I wish I could be a bird just to fly over mountains.",
    "Every trail teaches me patience.",
    "Why do trail signs always look faded right when you need them?",
    "I love spotting little lizards on warm rocks.",
    "Camping under green trees feels safer somehow.",
    "The crunch of leaves is one of my favorite sounds.",
    "I wish every day could end at a mountain lake.",
    "Sometimes I think nature is whispering secrets we don’t hear.",
    "The green of spring is different from summer green.",
    "Hiking makes food taste better.",
    "I like the way shadows move in forests.",
    "Steep trails test more than just muscles.",
    "Why do shoes always come untied halfway up a hill?",
    "Green hills always feel inviting.",
    "The forest feels alive even when it’s silent.",
    "I like the rhythm of walking uphill.",
    "I wish I could bottle the smell of pine needles.",
    "My favorite trails are the hidden ones.",
    "Sometimes I get jealous of plants just standing still and thriving.",
    "Green plants climbing rocks always amaze me.",
    "Why do mosquitoes know exactly where to bite?",
    "I always feel lighter on the way back.",
    "A trail with streams is my favorite kind.",
    "Hiking in the morning feels different than in the evening.",
    "Every green leaf looks like a different brushstroke.",
    "I like how moss softens everything it touches.",
    "Some paths feel like they’ve been waiting just for me.",
    "I wish I could grow a garden as wild as a forest.",
    "Sometimes my legs complain, but my heart doesn’t.",
    "Why do I always forget sunscreen?",
    "The greenest places feel the most healing.",
    "I love the way light dances through branches.",
    "I think climbing over roots makes me stronger.",
    "Green valleys always look like a painting.",
    "Sometimes silence on a trail is the best company.",
    "I like how hiking teaches me to slow down.",
    "I wish I could bring every friend to my favorite trails.",
    "Some of my best ideas come mid-hike.",
    "Green mountains remind me how small I am.",
    "Why do water bladders always leak at the worst times?",
    "I always feel proud when I finish a tough hike.",
    "The earth feels more alive in green places.",
    "Sometimes I just stop to breathe and that’s enough.",
    "I think trees are the best storytellers.",
    "Green fields remind me of freedom.",
    "I love the sound of boots on gravel paths.",
    "Every trail has its own personality.",
    "I wish I could sleep under the stars more often.",
    "Sometimes the hardest part is starting.",
    "Green plants always grow toward the light—so should I.",
    "Why do jackets feel too hot uphill but too cold downhill?",
    "The more I hike, the more grateful I feel.",
    "Sometimes a single tree can make my day.",
    "Green is endless when you look closely.",
    "I think nature makes me a better person.",
    "I’d rather be on a trail than almost anywhere else.",
    "Even short hikes feel worth it.",
]

tasks = pd.read_csv('reflections.csv')

tasks.columns = [col.strip().replace(' ', '_').lower()
                 for col in tasks.columns]

names = ['Evelyn', 'Mia', 'Noah', 'Emma', 'Benjamin', 'Jack', 'Sofia', 'Nora', 'Mason', 'Leah',
         'Jackie', 'Charlotte', 'Samantha', 'Luna', 'Zoe', 'Henry', 'Gabriel', 'Hannah', 'Daniel',
         'Dessy', 'Layla', 'Olivia', 'Ruby', 'Luisa', 'Ella', 'Penelope', 'Ava', 'Aria', 'Matthew',
         'Alexander', 'Madison', 'Grayson', 'Zach', 'Sebastian', 'Amelia', 'Isabella', 'Chloe',
         'Harper', 'Levi', 'Ethan', 'Sarah', 'Aiden', 'Anna', 'Elijah', 'Ally', 'Aurora',
         'Victoria', 'Wyatt', 'Stella', 'Scarlett']

tasks['tag_id'] = 9
tasks['author'] = ['Ally'] * 97
tasks['location_from'] = ['Stow, MA'] * 97

tasks['created_at'] = pd.to_datetime(
    tasks['created_at']).dt.strftime('%Y-%m-%d %H:%M:%S')

tasks['content'] = ally_reflections

tasks.to_csv('gratitude.csv', index=False)
