import numpy as np
import pandas as pd

fitness_tasks = [
    "Go for a 10-minute walk",
    "Run 1 mile",
    "Do 10 push-ups",
    "Do 20 squats",
    "Stretch for 5 minutes",
    "Do 15 lunges on each leg",
    "Do a 30-second plank",
    "Do 20 jumping jacks",
    "Do 10 burpees",
    "Do 15 tricep dips",
    "Walk up and down stairs 5 times",
    "Do 20 mountain climbers",
    "Do 15 calf raises",
    "Try a 5-minute yoga routine",
    "Do 10 bicycle crunches",
    "Do 20 Russian twists",
    "Do 15 side lunges",
    "Do 10 pull-ups or assisted pull-ups",
    "Do 20 high knees",
    "Do a 1-minute wall sit",
    "Go for a 15-minute jog",
    "Do 10 step-ups on a bench",
    "Do 10 push-ups with rotation",
    "Do 15 glute bridges",
    "Do 10 superman lifts",
    "Do 20 side leg raises",
    "Do 15 shoulder taps",
    "Do 10 diamond push-ups",
    "Do 20 skater jumps",
    "Do 10 pike push-ups",
    "Do 15 sumo squats",
    "Do 20 butt kicks",
    "Do 10 side planks each side",
    "Do 15 reverse lunges each leg",
    "Do 20 star jumps",
    "Do 10 hollow body holds",
    "Do 15 bird dogs",
    "Do a 20-minute brisk walk",
    "Do 15 push-ups on knees",
    "Do 30-second plank with leg lift",
    "Do 20 jumping lunges",
    "Do 15 incline push-ups",
    "Do 10 wall push-ups",
    "Do 15 seated leg raises",
    "Do 10 burpee tuck jumps",
    "Do 15 jumping squats",
    "Do 20 crunches",
    "Do 10 box jumps",
    "Do 15 frog jumps",
    "Do a 10-minute skipping rope session",
    "Do 10 clapping push-ups",
    "Do 20 plank jacks",
    "Do 15 lateral lunges",
    "Do 10 push-ups to side plank",
    "Do 15 hamstring curls",
    "Do 20 leg swings",
    "Do 10 pike jumps",
    "Do 15 glute kickbacks",
    "Do 20 standing side crunches",
    "Do 10 chest press with weights",
    "Do 15 bicep curls with weights",
    "Do 20 front raises with weights",
    "Do 10 overhead tricep extensions",
    "Do 15 shoulder presses with weights",
    "Do 10 bent-over rows with weights",
    "Do a 15-minute bike ride",
    "Do a 10-minute treadmill walk",
    "Do a 20-minute outdoor walk",
    "Do a 5-minute dynamic stretch routine",
    "Do a 10-minute HIIT session",
    "Do 15 plank shoulder taps",
    "Do 20 side-to-side hops",
    "Do 10 reverse crunches",
    "Do 15 heel touches",
    "Do 20 standing calf raises",
    "Do a 5-minute core routine",
    "Do 10 tricep push-ups",
    "Do 15 push-ups with claps",
    "Do a 15-minute Pilates session",
    "Do 10 burpee push-ups",
    "Do 20 alternating lunges",
    "Do 15 sumo squats with pulses",
    "Do a 20-minute jog",
    "Do 10 side lunges with reach",
    "Do 15 wall push-ups",
    "Do 20 reverse lunges with knee lift",
    "Do 10 kneeling side planks",
    "Do 15 single-leg deadlifts",
    "Do 20 plank toe taps",
    "Do 10 push-up to plank jacks",
    "Do 15 hip bridges with pulse",
    "Do 20 mountain climbers slow",
    "Do a 10-minute jump rope",
    "Do 15 squat pulses",
    "Do 10 push-up to T rotations",
    "Do 20 alternating high knees",
    "Do 15 donkey kicks each leg",
    "Do 10 side-lying leg lifts",
    "Do a 10-minute brisk walk",
    "Do 15 chair dips",
    "Do 20 jumping jacks slow",
    "Do 10 push-ups with rotation",
    "Do 15 bodyweight squats slow",
    "Do 20 plank shoulder taps",
    "Do a 5-minute mobility routine",
    "Do 15 step-ups with knee raise",
    "Do 10 burpees slow",
    "Do 20 standing marches",
    "Do 15 front lunges",
    "Do 10 diamond push-ups slow",
    "Do 20 side steps",
    "Do a 10-minute bike session",
    "Do 15 seated twists",
    "Do 10 jumping squats slow"
]

tasks = pd.read_csv('fitness_tasks.csv')

tasks.columns = [col.strip().replace(' ', '_').lower()
                 for col in tasks.columns]

names = ['Evelyn', 'Mia', 'Noah', 'Emma', 'Benjamin', 'Jack', 'Sofia', 'Nora', 'Mason', 'Leah',
         'Jackie', 'Charlotte', 'Samantha', 'Luna', 'Zoe', 'Henry', 'Gabriel', 'Hannah', 'Daniel',
         'Dessy', 'Layla', 'Olivia', 'Ruby', 'Luisa', 'Ella', 'Penelope', 'Ava', 'Aria', 'Matthew',
         'Alexander', 'Madison', 'Grayson', 'Zach', 'Sebastian', 'Amelia', 'Isabella', 'Chloe',
         'Harper', 'Levi', 'Ethan', 'Sarah', 'Aiden', 'Anna', 'Elijah', 'Ally', 'Aurora',
         'Victoria', 'Wyatt', 'Stella', 'Scarlett']

tasks.drop('tag', inplace=True, axis=1)
tasks['tag_id'] = 2
tasks['author'] = np.random.choice(names, size=len(tasks), replace=True)

tasks['created_at'] = pd.to_datetime(
    tasks['created_at']).dt.strftime('%Y-%m-%d %H:%M:%S')

tasks.to_csv('excercise.csv', index=False)
